import {
  Activity,
  Apple,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Award,
  Banknote,
  Bed,
  Bell,
  BookOpen,
  Calendar,
  CalendarCheck,
  Camera,
  ChartColumn,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleAlert,
  CircleCheck,
  CirclePlus,
  CircleX,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Copy,
  Crown,
  DollarSign,
  Download,
  Droplet,
  Droplets,
  Dumbbell,
  Ellipsis,
  Eye,
  EyeOff,
  FileText,
  Flame,
  Footprints,
  Gauge,
  GraduationCap,
  Heart,
  HeartPulse,
  House,
  Image as ImageGlyph,
  Images,
  Info,
  LayoutDashboard,
  Link as LinkGlyph,
  List,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Medal,
  MessageCircle,
  MessageSquare,
  Minus,
  Moon,
  NotebookPen,
  PartyPopper,
  Pause,
  Pencil,
  Phone,
  Play,
  Plus,
  QrCode,
  RefreshCw,
  Repeat,
  Rocket,
  Ruler,
  Salad,
  Scale,
  Search,
  Send,
  Settings,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Smartphone,
  Sparkles,
  SquarePen,
  Star,
  Sun,
  Target,
  Timer,
  Trash2,
  TrendingUp,
  Trophy,
  TriangleAlert,
  User,
  UserPlus,
  Users,
  Utensils,
  Video,
  Wallet,
  Weight,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react-native";
import { palette } from "../../lib/design/tokens";

/**
 * Curated, verified icon vocabulary for Projeto Gaab. Screens use these semantic
 * names via <AppIcon name="..." /> so iconography stays consistent and no screen
 * can reference an icon that does not exist.
 */
export const ICONS = {
  // Navigation / domains
  home: House,
  workout: Dumbbell,
  diet: Salad,
  food: Utensils,
  apple: Apple,
  progress: ChartColumn,
  trend: TrendingUp,
  activity: Activity,
  social: Users,
  user: User,
  "user-add": UserPlus,
  chat: MessageCircle,
  message: MessageSquare,
  courses: GraduationCap,
  dashboard: LayoutDashboard,
  financial: Wallet,
  money: DollarSign,
  banknote: Banknote,
  // Roles / moderation
  shield: Shield,
  moderation: ShieldCheck,
  "shield-alert": ShieldAlert,
  // Engagement
  bell: Bell,
  calendar: Calendar,
  "calendar-check": CalendarCheck,
  streak: Flame,
  trophy: Trophy,
  medal: Medal,
  award: Award,
  target: Target,
  crown: Crown,
  celebrate: PartyPopper,
  rocket: Rocket,
  sparkles: Sparkles,
  star: Star,
  // Controls
  plus: Plus,
  minus: Minus,
  "add-circle": CirclePlus,
  "chevron-right": ChevronRight,
  "chevron-left": ChevronLeft,
  "chevron-down": ChevronDown,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  external: ArrowUpRight,
  more: Ellipsis,
  settings: Settings,
  search: Search,
  list: List,
  edit: SquarePen,
  pencil: Pencil,
  trash: Trash2,
  copy: Copy,
  share: Share2,
  download: Download,
  refresh: RefreshCw,
  repeat: Repeat,
  // Media / capture
  camera: Camera,
  image: ImageGlyph,
  photos: Images,
  video: Video,
  qr: QrCode,
  link: LinkGlyph,
  // Body / health
  scale: Scale,
  ruler: Ruler,
  weight: Weight,
  heart: Heart,
  "heart-pulse": HeartPulse,
  steps: Footprints,
  water: Droplet,
  "water-multi": Droplets,
  energy: Zap,
  gauge: Gauge,
  sleep: Bed,
  moon: Moon,
  sun: Sun,
  // Status
  check: Check,
  "check-all": CheckCheck,
  "check-circle": CircleCheck,
  close: X,
  "x-circle": CircleX,
  info: Info,
  warning: TriangleAlert,
  alert: CircleAlert,
  clock: Clock,
  timer: Timer,
  play: Play,
  pause: Pause,
  eye: Eye,
  "eye-off": EyeOff,
  // Content / account
  book: BookOpen,
  clipboard: ClipboardList,
  "clipboard-check": ClipboardCheck,
  notebook: NotebookPen,
  file: FileText,
  mail: Mail,
  phone: Phone,
  send: Send,
  lock: Lock,
  logout: LogOut,
  device: Smartphone,
  location: MapPin,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

interface AppIconProps {
  name: IconName;
  size?: number;
  color?: string;
  strokeWidth?: number;
  fill?: string;
}

/** Render a curated icon by semantic name with consistent defaults. */
export function AppIcon({ name, size = 20, color = palette.textSecondary, strokeWidth = 2, fill }: AppIconProps) {
  const Glyph = ICONS[name] ?? Circle;
  return <Glyph size={size} color={color} strokeWidth={strokeWidth} fill={fill} />;
}

/** Escape hatch: render any Lucide icon component with the same default conventions. */
export function Icon({
  icon: Glyph,
  size = 20,
  color = palette.textSecondary,
  strokeWidth = 2,
  fill,
}: {
  icon: LucideIcon;
  size?: number;
  color?: string;
  strokeWidth?: number;
  fill?: string;
}) {
  return <Glyph size={size} color={color} strokeWidth={strokeWidth} fill={fill} />;
}
